DROP TABLE IF EXISTS `CATEGORY`;
CREATE TABLE CATEGORY COMMENT '상위 카테고리' (
    CATEGORY_ID BIGINT AUTO_INCREMENT COMMENT '카테고리 PK',
    CATEGORY_NAME VARCHAR(50) NOT NULL COMMENT '카테고리 명',
    CATEGORY_SEQ INT NOT NULL COMMENT '카테고리 노출 순서',
    PARENT_CATEGORY_ID INT  COMMENT '상위 카테고리 PK',
    IS_DISPLAY TINYINT DEFAULT 0 NOT NULL COMMENT '노출 여부',
    UPDATED_AT datetime NOT NULL COMMENT '수정일시',
    CREATED_AT datetime NOT NULL COMMENT '생성일시',
    PRIMARY KEY (CATEGORY_ID)
);